[phases.build]
cmds = ["./gradlew clean build -x test"]

[phases.start]
cmd = "java -Dspring.profiles.active=prod -Dserver.port=$PORT -jar build/libs/MovieTrackerAPI-0.0.1-SNAPSHOT.jar"

[variables]
GRADLE_OPTS = "-Xmx2g -Dorg.gradle.daemon=false"
