[phases.build]
cmds = ["./gradlew clean bootJar -x test"]

[phases.start]
cmd = "java -Dspring.profiles.active=prod -Dserver.port=$PORT -jar build/libs/*.jar"

[variables]
GRADLE_OPTS = "-Xmx2g -Dorg.gradle.daemon=false"
