spring:
  application:
    name: MovieTrackerAPI
  
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:devdb}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop  # Change to 'validate' in production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope:
              - openid
              - email
              - profile
          facebook:
            client-id: ${FACEBOOK_CLIENT_ID:your-facebook-client-id}
            client-secret: ${FACEBOOK_CLIENT_SECRET:your-facebook-client-secret}
            scope:
              - email
              - public_profile
          apple:
            client-id: ${APPLE_CLIENT_ID:your-apple-client-id}
            client-secret: ${APPLE_CLIENT_SECRET:your-apple-client-secret}
            scope:
              - email
              - name
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          apple:
            authorization-uri: https://appleid.apple.com/auth/authorize
            token-uri: https://appleid.apple.com/auth/token
            jwk-set-uri: https://appleid.apple.com/auth/keys
            user-info-uri: https://appleid.apple.com/auth/userinfo
            user-name-attribute: sub

# Custom authentication configuration
app:
  auth:
    local-auth-enabled: ${LOCAL_AUTH_ENABLED:true}
    oauth2-enabled: ${OAUTH2_ENABLED:true}
    jwt:
      secret: ${JWT_SECRET:movieTracker2024SecretKeyThatIsLongEnoughForHS256Algorithm}
      expiration-hours: ${JWT_EXPIRATION_HOURS:1}
  oauth2:
    redirect-uri: ${OAUTH2_REDIRECT_URI:http://localhost:3001/auth/callback-v2}
  api-base-url: ${API_BASE_URL:http://localhost:8081}

# GraphQL configuration
dgs:
  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql

# Logging
logging:
  level:
    com.movietracker.api: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
