spring:
  application:
    name: MovieTrackerAPI
  
  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:devdb}
    username: ${DATABASE_USERNAME:sa}
    password: ${DATABASE_PASSWORD:}
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop  # Change to 'validate' in production
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope:
              - email
              - profile
          github:
            client-id: ${GITHUB_CLIENT_ID:your-github-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:your-github-client-secret}
            scope:
              - user:email
              - read:user

# Custom authentication configuration
app:
  auth:
    local-auth-enabled: ${LOCAL_AUTH_ENABLED:true}
    oauth2-enabled: ${OAUTH2_ENABLED:false}
    jwt:
      secret: ${JWT_SECRET:movieTracker2024SecretKeyThatIsLongEnoughForHS256Algorithm}
      expiration-hours: ${JWT_EXPIRATION_HOURS:1}

# GraphQL configuration
dgs:
  graphql:
    path: /graphql
    graphiql:
      enabled: true
      path: /graphiql

# Logging
logging:
  level:
    com.movietracker.api: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
